CREATE TABLE `toon_count` (
  `USER_ID` varchar(45) NOT NULL,
  `GENRE_ACTION` int DEFAULT '0',
  `GENRE_ROMANCE` int DEFAULT '0',
  `GENRE_DRAMA` int DEFAULT '0',
  `GENRE_FANTASY` int DEFAULT '0',
  `GENRE_COMEDY` int DEFAULT '0',
  `GENRE_THRILLER` int DEFAULT '0',
  `GENRE_ACADEMY` int DEFAULT '0',
  PRIMARY KEY (`USER_ID`),
  CONSTRAINT `USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `user_table` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
