CREATE TABLE USER(
USER_ID INT NOT NULL PRIMARY KEY,
USER_PASSWORD VARCHAR(45) NOT NULL,
USER_NICKNAME VARCHAR(45) NOT NULL,
USER_PICK1 VARCHAR(45),
USER_PICK2 VARCHAR(45),
USER_PICK3 VARCHAR(45)
)
